name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
    matrix:
      os: [ubuntu-latest]
      python_version:
        "3.8.8"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: ${{ matrix.python_version }}

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      - name: Run Run tests
        run: pytest