"""Initial Migration

Revision ID: 138cc6ed918f
Revises: 
Create Date: 2023-11-04 17:46:06.209935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138cc6ed918f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
