"""Added Predications

Revision ID: 59530707e50a
Revises: 138cc6ed918f
Create Date: 2023-11-04 17:52:44.064265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59530707e50a'
down_revision = '138cc6ed918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('pred_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predications')
    # ### end Alembic commands ###
