"""initial

Revision ID: 6a59660058d7
Revises: 
Create Date: 2023-11-04 18:45:36.744322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a59660058d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('pred_type', sa.String(length=100), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predications')
    op.drop_table('articles')
    # ### end Alembic commands ###
