"""predications foreign key

Revision ID: 72f51568e4b8
Revises: 59530707e50a
Create Date: 2023-11-04 18:30:28.506148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f51568e4b8'
down_revision = '59530707e50a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###
